import './globals.css'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box';
import Image from 'next/image';
import logo from '../../public/ecomm_logo.png'
import { IoIosCart } from 'react-icons/io'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // console.log(children);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box className='navbar' sx={{ color: '#000', mx: 1.5 }}>
          <Box className='nav-dsk' sx={{ py: '16px', display: { xs: 'none', sm: 'flex' }, alignItems: 'center', justifyContent: 'space-between' }}>
            <Box display={'flex'} alignItems={'center'} gap={'32px'}>
              <Box><Image src={logo} alt='no_img' width={'182'} /></Box>
              <Box display={'flex'} alignItems={'center'} gap={'16px'}>
                <Box>All Products</Box>
                <Box>List</Box>
              </Box>
            </Box>
            <Box display={'flex'} alignItems={'center'} gap={'16px'}>
              <Box>About Us</Box>
              <Box>My Account</Box>
              <Box fontWeight={'600'} color={'#78909c'}>&#8377;0.00</Box>
              <Box position={'relative'} height={'22px'}>
                <IoIosCart size={'22px'} color='#78909c' />
                <Box position={'absolute'} sx={{ backgroundColor: '#78909c', top: -8, right: -8, height: '16px', width: '16px', textAlign: 'center', borderRadius: '50%', fontSize: '12px', fontWeight: '600' }}>0</Box>
              </Box>
            </Box>
          </Box>
          <Box className='nav-mob'>
            <Box></Box>
            <Box></Box>
            <Box></Box>
          </Box>
        </Box>
        <Box>{children}</Box>
        <Box>v</Box>
      </body>
    </html>
  )
}
