import './globals.css'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // console.log(children);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box>a</Box>
        <Box>{children}</Box>
        <Box>v</Box>
      </body>
    </html>
  )
}
